name: Build APK

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          # Устанавливаем совместимые версии autoconf и libtool
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
            autoconf=2.71-2 libtool=2.4.7-5 pkg-config zlib1g-dev libffi-dev libssl-dev

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install --upgrade cython
          pip install buildozer

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: youtube-downloader-app
          path: bin/*.apk
